In [1]:
import tensorflow as tf
x = tf.constant(35)
y = x+5
print(y)

/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Tensor("add:0", shape=(), dtype=int32)


In [2]:
print(tf.Session.run(y)) #note wierd API capitlization and cammel case

TypeError: run() missing 1 required positional argument: 'fetches'

In [3]:
sess = tf.Session() #launches graph
print(sess.run(y))

40


In [4]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(y*x))

35
40
1400


In [5]:
"""
with open('output.txt', 'w') as f:
    f.write('Hi there!')
"""

"\nwith open('output.txt', 'w') as f:\n    f.write('Hi there!')\n"

In [6]:
with tf.Session() as sess:
    add=sess.run(tf.add(y,x))
    mul=sess.run(tf.multiply(y,x)) #ALL the math functions are built in, always use the most complex one
    print(add) #note that not assigning before print won't work
    print(mul)

75
1400


In [7]:
matrix1 = tf.constant([[3., 3.]])

In [8]:
#remind you of something?
import numpy as np
a=np.array([[3.,3.]])
print(a)

[[3. 3.]]


In [9]:
matrix2 = tf.constant([[2.],[2.]])

with tf.Session() as sess:
    result = sess.run(tf.matmul(matrix1, matrix2))
    print(result)

[[12.]]


In [10]:
w=tf.Variable(3.) #note float/int infered in compilation
with tf.Session() as sess:
    result = w.assign_add(1.)
    print(result)

Tensor("AssignAdd:0", shape=(), dtype=float32_ref)


In [11]:
w=tf.Variable(3.) #note float/int infered in compilation
with tf.Session() as sess:
    sess.run(w.initializer) #note this
    result = sess.run(w.assign_add(1.))
    print(result)

4.0


In [12]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) #note this
    result = sess.run(w.assign_add(1.))
    print(result)

4.0


In [13]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
      print(sess.run(y))  # ERROR: will fail because x was not fed.

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [1024,1024]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-5fa136f412f1>", line 1, in <module>
    x = tf.placeholder(tf.float32, shape=(1024, 1024))
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1770, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4551, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3270, in create_op
    op_def=op_def)
  File "/Users/noahkasmanoff/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [1024,1024]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [14]:
with tf.Session() as sess:
    rand_array = np.random.rand(1024, 1024)
    print(sess.run(y, feed_dict={x: rand_array})) 

[[261.8432  262.98804 263.68127 ... 264.19443 263.1109  249.45236]
 [263.6447  259.17307 264.97537 ... 262.35355 267.8431  250.62225]
 [264.40045 258.53418 264.48114 ... 262.46097 262.75424 250.09637]
 ...
 [251.6973  252.68462 257.30963 ... 255.02376 251.43953 241.93214]
 [253.777   255.34196 263.4357  ... 258.28046 254.08774 243.04651]
 [254.38794 251.85713 251.8665  ... 255.8847  252.1536  243.20284]]
