In [65]:
from nba_py import team
import pandas as pd
import numpy as np
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

height has been deprecated.



In [88]:
bos = team.TeamLastNGamesSplits(team_id='1610612738')

In [89]:
bosdf = bos.last20()

In [91]:
bosdf

GROUP_SET    GROUP_VALUE  GP   W  L  W_PCT   MIN   FGM   FGA  FG_PCT  FG3M  FG3A  FG3_PCT   FTM   FTA  FT_PCT  OREB  DREB   REB   AST   TOV  STL  BLK  BLKA    PF   PFD    PTS  PLUS_MINUS  GP_RANK  W_RANK  L_RANK  W_PCT_RANK  MIN_RANK  FGM_RANK  FGA_RANK  FG_PCT_RANK  FG3M_RANK  FG3A_RANK  FG3_PCT_RANK  FTM_RANK  FTA_RANK  FT_PCT_RANK  OREB_RANK  DREB_RANK  REB_RANK  AST_RANK  TOV_RANK  STL_RANK  BLK_RANK  BLKA_RANK  PF_RANK  PFD_RANK  PTS_RANK  PLUS_MINUS_RANK  CFID       CFPARAMS
0  Last 20 Games  Last 20 Games  20  12  8    0.6  48.5  39.1  84.8   0.461  10.6  26.5    0.399  16.5  20.9   0.787  10.0  35.1  45.1  23.3  15.0  8.0  4.0   4.6  17.8  20.1  105.2         2.8        1       1       1           1         1         1         1            1          1          1             1         1         1            1          1          1         1         1         1         1         1          1        1         1         1                1   161  Last 20 Games

In [4]:
teams = team.TeamList()

In [5]:
teamids =teams.info()

In [6]:
teamids = teamids[:-15]
teamids = teamids[['TEAM_ID','ABBREVIATION']]

teamids = teamids.rename(index=str, columns={"ABBREVIATION": "Team"})
teamids = teamids.replace('BKN','BRK')
teamids = teamids.sort_values('Team')


In [51]:
teamids = pd.get_dummies(teamids)

In [52]:
teamids

TEAM_ID  Team_ATL  Team_BOS  Team_BRK  Team_CHA  Team_CHI  Team_CLE  Team_DAL  Team_DEN  Team_DET  Team_GSW  Team_HOU  Team_IND  Team_LAC  Team_LAL  Team_MEM  Team_MIA  Team_MIL  Team_MIN  Team_NOP  Team_NYK  Team_OKC  Team_ORL  Team_PHI  Team_PHX  Team_POR  Team_SAC  Team_SAS  Team_TOR  Team_UTA  Team_WAS
0   1610612737         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
1   1610612738         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
14  1610612751         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
29  1610612766         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
4   1610612741         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
2   1610612739         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
5   1610612742         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
6   1610612743         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
28  1610612765         0         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
7   1610612744         0         0         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
8   1610612745         0         0         0         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0
17  1610612754         0         0         0         0         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0   

In [59]:
teamids.loc[teamids['TEAM_ID'] == 1610612739].values[0,1:]
#returns array of the teams ID

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
def get_splits(TEAMABR,ten=False,twenty=True):
    """returns the splits of a team over the past N days. Will consider changing this to a from - to thing for different dates. 
    """
    
    teams = team.TeamList()
    teamids = teams.info()
    teamids = teamids[:-15]
    teamids = teamids[['TEAM_ID','ABBREVIATION']]

    teamids = teamids.rename(index=str, columns={"ABBREVIATION": "Team"})
    teamids = teamids.replace('BKN','BRK')
    teamids = teamids.sort_values('Team')

    TEAM_ID = teamids.loc[teamids['Team'] == TEAMABR].values[0,0]
    teamids = pd.get_dummies(teamids)
    teamarray = teamids.loc[teamids['TEAM_ID'] == TEAM_ID].values[0,1:]


    TEAM = team.TeamLastNGamesSplits(team_id=TEAM_ID)
    if ten:
        df = TEAM.last10()
    if twenty:
        df = TEAM.last20()
    df = df[['OREB','DREB','REB','PF','STL','TOV','BLK','FG3_PCT','FG_PCT','FT_PCT']].values
    
    teamsplits = np.concatenate((df[0],teamarray))
    return teamsplits



In [93]:
getsplits('BOS',5)

array([ 9.9  , 33.6  , 43.5  , 16.9  ,  9.1  , 14.7  ,  3.8  ,  0.391,
        0.457,  0.775,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ])

In [73]:
teamstats = np.array([[ 6.4  , 35.4  , 41.8  , 19.   ,  7.1  , 14.6  ,  7.1  ,  0.383,
          0.462,  0.736]])
teamcode = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]) 

In [74]:
np.shape(teamcode)

(30,)

In [75]:
np.shape(teamstats)

(1, 10)

In [77]:
np.concatenate((teamstats[0],teamcode))

array([ 6.4  , 35.4  , 41.8  , 19.   ,  7.1  , 14.6  ,  7.1  ,  0.383,
        0.462,  0.736,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ])

In [10]:
teams = team.TeamList()
df = teams.info()
df

LEAGUE_ID     TEAM_ID MIN_YEAR MAX_YEAR ABBREVIATION
0         00  1610612737     1949     2017          ATL
1         00  1610612738     1946     2017          BOS
2         00  1610612739     1970     2017          CLE
3         00  1610612740     2002     2017          NOP
4         00  1610612741     1966     2017          CHI
5         00  1610612742     1980     2017          DAL
6         00  1610612743     1976     2017          DEN
7         00  1610612744     1946     2017          GSW
8         00  1610612745     1967     2017          HOU
9         00  1610612746     1970     2017          LAC
10        00  1610612747     1948     2017          LAL
11        00  1610612748     1988     2017          MIA
12        00  1610612749     1968     2017          MIL
13        00  1610612750     1989     2017          MIN
14        00  1610612751     1976     2017          BKN
15        00  1610612752     1946     2017          NYK
16        00  1610612753     1989     2017          ORL
17        00  1610612754     1976     2017          IND
18        00  1610612755     1949     2017          PHI
19        00  1610612756     1968     2017          PHX
20        00  1610612757     1970     2017          POR
21        00  1610612758     1948     2017          SAC
22        00  1610612759     1976     2017          SAS
23        00  1610612760     1967     2017          OKC
24        00  1610612761     1995     2017          TOR
25        00  1610612762     1974     2017          UTA
26        00  1610612763     1995     2017          MEM
27        00  1610612764     1961     2017          WAS
28        00  1610612765     1948     2017          DET
29        00  1610612766     1988     2017          CHA
30        00  1610610031     1946     1946         None
31        00  1610610029     1948     1948         None
32        00  1610610025     1946     1949         None
33        00  1610610034     1946     1949         None
34        00  1610610036     1946     1950         None
35        00  1610610024     1947     1954         None
36        00  1610610027     1949     1949         None
37        00  1610610030     1949     1952         None
38        00  1610610033     1949     1949         None
39        00  1610610037     1949     1949         None
40        00  1610610023     1949     1949         None
41        00  1610610026     1946     1946         None
42        00  1610610028     1946     1946         None
43        00  1610610032     1946     1948         None
44        00  1610610035     1946     1946         None

In [12]:
df.loc[df['ABBREVIATION'] == 'ATL'].values[0,1]


1610612737